import {
  Scale,
  Smile,
  Newspaper,
  Brain,
} from "lucide-react";

import Container from "../layout/Container";
import FeatureCard from "./FeatureCard";

export default function Features() {
  const features = [
    {
      icon: <Scale size={28} />,
      title: "Bias Detection",
      description:
        "Discover whether an article leans left, right, or remains neutral using AI analysis.",
    },
    {
      icon: <Smile size={28} />,
      title: "Sentiment Analysis",
      description:
        "Understand the emotional tone behind every article before reading it.",
    },
    {
      icon: <Brain size={28} />,
      title: "AI Summary",
      description:
        "Read concise summaries generated by AI to save time and understand the key points.",
    },
    {
      icon: <Newspaper size={28} />,
      title: "Trusted Sources",
      description:
        "Search and analyze articles from multiple news publishers in one place.",
    },
  ];

  return (
    <section className="py-24">
      <Container>
        <div className="text-center max-w-3xl mx-auto">
          <h2 className="text-4xl font-bold text-slate-900">
            Why use AI News Bias Detector?
          </h2>

          <p className="mt-5 text-lg text-slate-600">
            Analyze news smarter with AI-powered insights that help you
            identify bias, sentiment, and credibility in seconds.
          </p>
        </div>

        <div className="mt-16 grid gap-8 md:grid-cols-2 xl:grid-cols-4">
          {features.map((feature) => (
            <FeatureCard
              key={feature.title}
              {...feature}
            />
          ))}
        </div>
      </Container>
    </section>
  );
}